export const mockInfluencers = [
  {
    id: "inf-1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    bio: "Sustainable fashion advocate | 15K followers",
    followers: 15000,
    engagement: 8.5,
    category: "Fashion",
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    rating: 4.8,
  },
  {
    id: "inf-2",
    name: "Maya Patel",
    email: "maya@example.com",
    bio: "Beauty & wellness creator | 22K followers",
    followers: 22000,
    engagement: 9.2,
    category: "Beauty",
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya",
    rating: 4.9,
  },
  {
    id: "inf-3",
    name: "Jessica Rodriguez",
    email: "jessica@example.com",
    bio: "Eco-friendly lifestyle | 18K followers",
    followers: 18000,
    engagement: 7.8,
    category: "Lifestyle",
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    rating: 4.6,
  },
  {
    id: "inf-4",
    name: "Aisha Williams",
    email: "aisha@example.com",
    bio: "Tech & innovation enthusiast | 25K followers",
    followers: 25000,
    engagement: 8.9,
    category: "Tech",
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha",
    rating: 4.7,
  },
]

export const mockBusinesses = [
  {
    id: "bus-1",
    name: "Artisan Ceramics Co",
    email: "hello@artisanceramics.com",
    bio: "Handmade ceramic products for modern homes",
    followers: 8500,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ceramics",
    rating: 4.7,
  },
  {
    id: "bus-2",
    name: "Eco Threads",
    email: "info@ecothreads.com",
    bio: "Sustainable fashion brand for conscious consumers",
    followers: 12000,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=EcoThreads",
    rating: 4.8,
  },
  {
    id: "bus-3",
    name: "Natural Beauty Lab",
    email: "contact@naturalbeautylab.com",
    bio: "Organic skincare and wellness products",
    followers: 15000,
    verified: true,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BeautyLab",
    rating: 4.9,
  },
]

export const mockCampaigns = [
  {
    id: "camp-1",
    name: "Summer Collection Launch",
    status: "active",
    budget: 500,
    influencers: 3,
    startDate: "2025-01-15",
    endDate: "2025-02-15",
    engagement: 12500,
  },
  {
    id: "camp-2",
    name: "Spring Promotion",
    status: "completed",
    budget: 300,
    influencers: 2,
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    engagement: 8900,
  },
  {
    id: "camp-3",
    name: "New Product Reveal",
    status: "pending",
    budget: 750,
    influencers: 5,
    startDate: "2025-02-01",
    endDate: "2025-03-01",
    engagement: 0,
  },
]

export const mockInfluencerCollaborations = [
  {
    id: "collab-1",
    businessName: "Artisan Ceramics Co",
    campaignName: "Summer Collection Launch",
    status: "pending",
    budget: 200,
    message: "We'd love to have you promote our new summer collection!",
    createdAt: "2025-01-12",
  },
  {
    id: "collab-2",
    businessName: "Eco Threads",
    campaignName: "Spring Promotion",
    status: "accepted",
    budget: 150,
    message: "Perfect fit for your sustainable lifestyle content",
    createdAt: "2025-01-05",
  },
  {
    id: "collab-3",
    businessName: "Natural Beauty Lab",
    campaignName: "Product Launch",
    status: "completed",
    budget: 250,
    message: "Great collaboration! Your audience loved our products.",
    createdAt: "2024-12-20",
  },
]

export const mockRequests = [
  {
    id: "req-1",
    influencerId: "inf-1",
    influencerName: "Sarah Chen",
    campaignName: "Summer Collection Launch",
    status: "pending",
    message: "Interested in collaborating on your summer collection!",
    createdAt: "2025-01-10",
  },
  {
    id: "req-2",
    influencerId: "inf-2",
    influencerName: "Maya Patel",
    campaignName: "Summer Collection Launch",
    status: "accepted",
    message: "Love your brand! Let's work together.",
    createdAt: "2025-01-08",
  },
]

export const mockPendingVerifications = [
  {
    id: "ver-1",
    name: "Luna Designs",
    type: "business",
    email: "hello@lunadesigns.com",
    bio: "Handmade jewelry and accessories",
    followers: 5000,
    submittedAt: "2025-01-15",
    documents: ["business_license.pdf", "tax_id.pdf"],
  },
  {
    id: "ver-2",
    name: "Alex Thompson",
    type: "influencer",
    email: "alex@example.com",
    bio: "Fashion and lifestyle content creator",
    followers: 12000,
    submittedAt: "2025-01-14",
    documents: ["id_verification.pdf", "follower_proof.pdf"],
  },
  {
    id: "ver-3",
    name: "Craft & Co",
    type: "business",
    email: "info@craftco.com",
    bio: "Sustainable craft supplies",
    followers: 8000,
    submittedAt: "2025-01-13",
    documents: ["business_license.pdf", "insurance.pdf"],
  },
  {
    id: "ver-4",
    name: "Jordan Lee",
    type: "influencer",
    email: "jordan@example.com",
    bio: "Beauty and wellness influencer",
    followers: 18000,
    submittedAt: "2025-01-12",
    documents: ["id_verification.pdf", "follower_proof.pdf"],
  },
]

export const mockVerificationHistory = [
  {
    id: "hist-1",
    name: "Sarah Chen",
    type: "influencer",
    status: "approved",
    verifiedAt: "2025-01-10",
    verifiedBy: "Admin User",
  },
  {
    id: "hist-2",
    name: "Artisan Ceramics Co",
    type: "business",
    status: "approved",
    verifiedAt: "2025-01-09",
    verifiedBy: "Admin User",
  },
  {
    id: "hist-3",
    name: "Test Account",
    type: "influencer",
    status: "rejected",
    verifiedAt: "2025-01-08",
    verifiedBy: "Admin User",
  },
]
